services:
    image: ptylenda/kimchi-docker
    resources:
            limits:
              cpus: 0.75
              memory: 8G
            reservations:
              cpus: 0.75
              memory: 8G
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - 8001:8001
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    stop_grace_period: 2m
