name: Tailscale - Docker

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chuẩn bị phần mềm
        run: |
          sudo apt update -y
          sudo apt install wget curl -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: cài win và khởi chạy
        run: |
          sudo chmod 666 /dev/kvm
          sudo mkdir /isos/
          wget https://raw.githubusercontent.com/bgopl092/ActionDocker/main/compose.yaml
          tailscale ip -4
          echo "thanh cong, ket noi bang port 8006 o trinh duyet Chrome"
          sudo docker run -it -p 8001:8001 -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ptylenda/kimchi-docker:latest /bin/bash
  notify:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Notify Slack and send eMail
        run: sleep 9999999999999999999999
